### ISSUE TITLE
erreur 

### ISSUE THREAD

**Issue by randomalea** [uiters/store-pattern#22]
j ai suivi les instructions
mais le probleme  
logining  ca prend de tempssssssssssssssssssssss
sans fin

**Comment by tvc12** [comment]
@randomalea try test with: 
**user**: admin
**pass**: admin

**Comment by randomalea** [comment]
bjr
ce n'est pas un problème d'authentification
je crois la liaison avec un serveur MySQL n'est pas bien effectue
pouvez nous présenter la méthode a suivre pour la préparation d'une liaison avec MySQL
ma méthode : 
1. j ai creer une base de donnes mysql sur un serveur payant
2. ensuite j' ai executer le script sql pour la creation des tables et donnes des tables
3.j'ai inserer le fichier index.php  ds le site  avec la modification
nom serveur   , nom base de donnees , user , mot de passe
4. j ai modifier la ligne ds le fichierevn.dart
const String URL_EXECUTE = 'http://www.geslogiweb.com/site/index.php"';

et ca marche pas

lorsque j'entre
admin
admin

ou

test
test

ou
tvc12
tvc12

CA prend beaucoup de temps sans accès au donnes ou déplacement vers les autres formulaire

**Comment by tvc12** [comment]
Sorry, i'm busy.
Can you take some screenshot for description error?

**Comment by tvc12** [comment]
ohh, i vissit your stie: http://www.geslogiweb.com/site/index.php
But chrome detected your site are damgerous.
I think you should try with a new domain
