### ISSUE TITLE
The getter 'length' was called on null.

### ISSUE THREAD

**Issue by federico2390** [uiters/store-pattern#27]
Hi I have downloaded this project I have followed the instructions to copy your .sql database file inside my "myphpadmin". I have tried with 'normal' and 'security' php files but without results and after I have paste my index.php address inside the code, how the your instruction. Yet the verision of the .sql database file is out of date (deprecated) and for this I have some problem when I import the your .sql database file inside the my "myphpadmin".
 Whenever I receive the following error:

Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length)

How can I solve this, please is there anyone that can help me?

**Comment by tvc12** [comment]
Thank you interested my projects, can you paste your error or screen it here? @federico2390

**Comment by federico2390** [comment]
![image](https://user-images.githubusercontent.com/42987961/73612800-50018a80-45ef-11ea-9571-7f7ea70a53db.jpg)

**Comment by tvc12** [comment]
i haven't enough info about your error? Try import database again, if you have problem screenshot it for me here
