### ISSUE TITLE
Migrate service to Dart language

### ISSUE THREAD

**Issue by 103cuong** [uiters/store-pattern#28]
**Why?**
> PHP is so bad and not for a new Flutter developer. Centralizing to Dart language is an easy way to learning Flutter.

**Comment by tvc12** [comment]
OMG! On Comming!

**Comment by 103cuong** [comment]
@tvc12 any updates?

**Comment by 103cuong** [comment]
Dart service is impossible, so Node is the better solution.
#37 
@tvc12
